{
 "title": "Main dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CI per language",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS \"time\",  language AS metric, count(*) as value FROM repository where LENGTH(language) > 1 and ci_cd = true GROUP BY language ORDER BY value desc LIMIT 10"
    }
   ]
  },
  {
   "title": "Tests per language",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS \"time\",  language AS metric, count(*) as value FROM repository where LENGTH(language) > 1 and tests = true GROUP BY language ORDER BY value desc LIMIT 10"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS \"time\",  name AS metric, commits as value FROM repository where LENGTH(name) > 1 ORDER BY commits desc LIMIT 10"
    }
   ]
  },
  {
   "title": "Number of repos per language",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS \"time\",  language AS metric, count(*) as value FROM repository where LENGTH(language) > 1 GROUP BY language ORDER BY value desc LIMIT 10"
    }
   ]
  }
 ]
}